# SPDX-FileCopyrightText: 2024 ash_slug contributors <https://github.com/ash-project/ash_slug/graphs.contributors>
#
# SPDX-License-Identifier: MIT

---
updates:
  - directory: /
    package-ecosystem: mix
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
version: 2
