# SPDX-FileCopyrightText: 2024 Rolf HÃ¥vard Blindheim
#
# SPDX-License-Identifier: MIT

---
updates:
  - directory: /
    package-ecosystem: mix
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
version: 2
